# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190212_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followings',
        ),
    ]
