# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190131_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='accent_color_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_color_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
