# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190131_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='accent_color_code',
            new_name='accent_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='bg_color_code',
            new_name='bg_color',
        ),
    ]
