# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190131_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colorGenres',
            field=models.BooleanField(default=True),
        ),
    ]
