# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190212_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
