# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_avatar_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='friend',
            new_name='follower',
        ),
    ]
