# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190212_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='genre',
        ),
    ]
