# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id_user',
            new_name='user',
        ),
    ]
