# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2019-02-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_avatar_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celularDataSavings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Theme'),
        ),
    ]
