# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-29 11:21
from __future__ import unicode_literals

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20190219_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=App.models.path_image_upload),
        ),
    ]
