# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='seen',
        ),
        migrations.AddField(
            model_name='movie',
            name='states',
            field=models.ManyToManyField(blank=True, to='App.State'),
        ),
    ]
