# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
