# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_episode', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('states', models.ManyToManyField(blank=True, to='App.State')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='App.Episode'),
        ),
    ]
