# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200117_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, to='App.Movie'),
        ),
        migrations.AddField(
            model_name='list',
            name='shows',
            field=models.ManyToManyField(blank=True, to='App.Show'),
        ),
    ]
