# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='App.Profile'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='App.Profile'),
        ),
    ]
