# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_episode_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='date_add',
            new_name='date_update',
        ),
    ]
