# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20190211_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
