# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200122_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='endpoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
