# Generated by Django 3.2.17 on 2023-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_profile_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qip',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='qpassword',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='qport',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='quser',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
