# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 15:49
from __future__ import unicode_literals

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20190211_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, height_field='height_image', null=True, upload_to=App.models.path_image_upload, width_field='width_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='width_image',
            field=models.IntegerField(default=0),
        ),
    ]
