# Generated by Django 3.2.17 on 2023-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20230208_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qpassword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qport',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quser',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
